version: "3.9"

networks:
  npm:
    name: npm
    driver: bridge

secrets:

  DB_ROOT_PWD:
    file: ./secrets/db_root_pwd.secret
  MYSQL_PWD:
    file: ./secrets/mysql_pwd.secret

services:

  # Nginx Proxy Manager - Expose your services easily and securely.
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped

    networks:
      - npm

    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
        
      - target: 81
        published: $PORT
        protocol: tcp
        mode: host
        
      - target: 443
        published: 443
        protocol: tcp
        mode: host

    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm_user"
      DB_MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PWD
      DB_MYSQL_NAME: "npm_db"

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

    secrets:
      - MYSQL_PWD

    depends_on:
      - db

  # MariaDB - The open source relational database.
  db:
    image: jc21/mariadb-aria
    restart: unless-stopped

    networks:
      - npm

    environment:
      MYSQL_ROOT_PASSWORD__FILE: /run/secrets/DB_ROOT_PWD
      MYSQL_DATABASE: "npm_db"
      MYSQL_USER: "npm_user"
      MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PWD

    volumes:
      - ./data/mysql:/var/lib/mysql

    secrets:
      - DB_ROOT_PWD
      - MYSQL_PWD

  # Watchtower - automating Docker container base image updates.
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always

    networks:
      - npm

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - TZ=$TZ
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_SCHEDULE=0 30 5 * * * # Everyday at 5:30
